package ru.pathcreator.pyc.rpc.serialization.serializer.sbe.model;

public enum SbeFieldKind {
    PRIMITIVE,
    BOXED_PRIMITIVE,
    BOOLEAN,
    BOXED_BOOLEAN,
    CHAR,
    BOXED_CHAR,
    ENUM,
    UUID,
    INSTANT,
    LOCAL_DATE,
    LOCAL_TIME,
    LOCAL_DATE_TIME,
    OFFSET_DATE_TIME,
    OFFSET_TIME,
    DURATION,
    PERIOD,
    YEAR,
    YEAR_MONTH,
    MONTH_DAY,
    ZONE_OFFSET,
    BIG_INTEGER,
    BIG_DECIMAL,
    STRING,
    BYTES,
    FIXED_STRING,
    FIXED_BYTES,
    NESTED_FIXED,
    REPEATING_GROUP,
    REPEATING_SCALAR,
    MAP,
    UNSUPPORTED
}